[package]
name = "sparrow"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
askama = "0.12.1"
axum = "0.7.9"
cpal = "0.15.3"
http = "1.2.0"
slog = "2.7.0"
slog-scope = "4.4.0"
slog-term = "2.9.1"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
